# Build a consumer using only the installed package, with no source include path.
if(NOT DEFINED OBDEECT_BUILD_DIR OR NOT DEFINED OBDEECT_SOURCE_DIR)
  message(FATAL_ERROR "OBDEECT_BUILD_DIR and OBDEECT_SOURCE_DIR are required")
endif()
set(prefix "${OBDEECT_BUILD_DIR}/consumer-install")
set(consumer "${OBDEECT_BUILD_DIR}/consumer")
file(REMOVE_RECURSE "${prefix}" "${consumer}")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${OBDEECT_BUILD_DIR}" --prefix "${prefix}"
                RESULT_VARIABLE result OUTPUT_QUIET)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Package installation failed: ${result}")
endif()
file(MAKE_DIRECTORY "${consumer}")
file(WRITE "${consumer}/CMakeLists.txt" "cmake_minimum_required(VERSION 3.20)\nproject(consumer LANGUAGES CXX)\nfind_package(obdeect CONFIG REQUIRED)\nadd_executable(consumer main.cpp)\ntarget_link_libraries(consumer PRIVATE obdeect::obdeect_core)\n")
file(WRITE "${consumer}/main.cpp" "#include <obdeect/math.hpp>\n#include <cmath>\nint main() { const obdeect::Vec3 value{3,4,0}; return std::abs(obdeect::norm(value)-5)>1.e-12; }\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${consumer}" -B "${consumer}/build"
                "-DCMAKE_PREFIX_PATH=${prefix}" RESULT_VARIABLE result OUTPUT_QUIET)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Installed package configuration failed: ${result}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${consumer}/build"
                RESULT_VARIABLE result OUTPUT_QUIET)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Installed consumer build failed: ${result}")
endif()
if(WIN32)
  set(binary "${consumer}/build/Debug/consumer.exe")
else()
  set(binary "${consumer}/build/consumer")
endif()
execute_process(COMMAND "${binary}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Installed consumer failed: ${result}")
endif()
